export const FETCH_DATA_START = 'FETCH_DATA_START'
export const FETCH_DATA_SUCCES = 'FETCH_DATA_SUCCES'
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'
export const SELECT_ITEM = 'SELECT_ITEM'
export const ADD_TO_CART = 'ADD_TO_CART'
export const DEC_CART_ITEM = 'DEC_CART_ITEM'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const OPEN_AUTH_MODAL = 'OPEN_AUTH_MODAL'
export const CLOSE_AUTH_MODAL = 'CLOSE_AUTH_MODAL'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const SET_COUNT_ON_PAGE = 'SET_COUNT_ON_PAGE'
export const SEARCH_ITEM = 'SEARCH_ITEM'



